import type { CSSProperties } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import {
  about,
  capabilities,
  education,
  experience,
  meta,
  profile,
  stackGroups,
} from "@/content/site";
import LightUp from "@/components/LightUp";
import Portrait from "@/components/Portrait";
import LocalTime from "@/components/islands/LocalTime";

const TITLE = `About — ${profile.short} Tehseen`;
const DESCRIPTION =
  "Muhammad Ammaad Tehseen — full-stack engineer in Lahore, Pakistan. How I work: the boring layers on purpose, instrument it before you need it, and production is not a staging environment.";

/**
 * The root share card, named explicitly. A page that sets its own openGraph
 * replaces the layout's whole object, and the card generated by
 * app/opengraph-image.tsx only attaches to the segment it lives in, so without
 * this line /about would share as a bare link.
 */
const SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${profile.name} — ${profile.role} in ${profile.location}`,
};

export const metadata: Metadata = {
  title: "About",
  description: DESCRIPTION,
  alternates: { canonical: "/about" },
  openGraph: {
    type: "profile",
    url: `${profile.site}/about`,
    siteName: meta.title,
    locale: "en_GB",
    title: TITLE,
    description: about.lede,
    images: [SHARE_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: about.lede,
    creator: "@MAmmaadTehseen",
    images: [SHARE_IMAGE],
  },
};

/** One section's worth of space: the site rhythm, applied once between sections rather than doubled. */
const SECTION = "mt-[clamp(96px,14vh,160px)]";

const stagger = (i: number) => ({ "--i": i }) as CSSProperties;

/**
 * Words set as a run of text with middots between them. The dots are
 * decoration, so they are hidden from screen readers, which hear a plain list.
 */
function Dotted({ items, className }: { items: string[]; className?: string }) {
  return (
    <ul className={`flex flex-wrap gap-x-2 gap-y-1 ${className ?? ""}`}>
      {items.map((item, index) => (
        <li key={item} className="inline-flex gap-x-2">
          {item}
          {index < items.length - 1 && (
            <span className="text-dim" aria-hidden="true">
              ·
            </span>
          )}
        </li>
      ))}
    </ul>
  );
}

/**
 * The long form: who, how, where, since when, with what.
 *
 * Nothing in the first viewport waits on anything. The h1 lights up in CSS
 * before hydration and the portrait is static (no window opening here; that
 * belongs to the home page), so the page paints finished. Reveals start at the
 * first section below the header, and only as dim, readable start states.
 */
export default function AboutPage() {
  return (
    <div className="frame pt-36 pb-[clamp(96px,14vh,160px)] md:pt-44">
      <header className="grid gap-12 lg:grid-cols-12 lg:gap-10">
        <div className="lg:col-span-7">
          <LightUp as="h1" step={50} text={about.lede} className="t-page" />
          <div className="mt-10 space-y-6">
            {about.body.map((paragraph) => (
              <p key={paragraph} className="t-body text-ink-2">
                {paragraph}
              </p>
            ))}
          </div>
        </div>

        <div className="lg:col-span-5 lg:pt-3">
          <Portrait
            variant="about"
            className="max-w-[420px] lg:ml-auto lg:max-w-[460px]"
            caption={
              <>
                <span className="block">{profile.location}</span>
                <LocalTime variant="sentence" />
              </>
            }
          />
        </div>
      </header>

      {/* three named positions, not a list of adjectives */}
      <section aria-labelledby="how-i-work" className={SECTION}>
        <h2 id="how-i-work" className="t-h2" data-reveal="focus">
          How I work
        </h2>
        <ul className="list border-line mt-12 border-t">
          {about.approach.map((item, index) => (
            <li
              key={item.title}
              className="row border-line grid gap-4 border-b py-8 md:grid-cols-12 md:gap-10 md:py-10"
              data-reveal="rise"
              style={stagger(index)}
            >
              <h3 className="t-h3 text-ink font-[350] md:col-span-5">
                {item.title}
              </h3>
              <p className="t-body text-ink-2 md:col-span-7">{item.body}</p>
            </li>
          ))}
        </ul>
      </section>

      {/* the section a recruiter scans first, so it stays plain and factual */}
      <section aria-labelledby="experience" className={SECTION}>
        <h2 id="experience" className="t-h2" data-reveal="focus">
          Experience
        </h2>
        <ol className="border-line mt-12 border-t">
          {experience.map((role, index) => (
            <li
              key={`${role.org}-${role.period}`}
              className="border-line grid gap-6 border-b py-10 lg:grid-cols-12 lg:gap-10"
              data-reveal="rise"
              style={stagger(index)}
            >
              <div className="lg:col-span-5">
                <p className="t-meta">{role.period}</p>
                <h3 className="t-h3 text-ink mt-3 font-[350]">{role.role}</h3>
                <p className="t-meta mt-3">
                  {role.org} · {role.location}
                </p>
              </div>
              <ul className="t-body text-ink-2 space-y-3 lg:col-span-7">
                {role.points.map((point) => (
                  <li key={point} className="flex gap-4">
                    <span
                      className="bg-line-strong mt-[0.84em] h-px w-3 shrink-0"
                      aria-hidden="true"
                    />
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ol>

        <div className="mt-16" data-reveal="rise">
          <h3 className="t-voice text-ink">Education</h3>
          <div className="border-line mt-6 grid gap-2 border-y py-6 lg:grid-cols-12 lg:gap-10">
            <p className="t-meta lg:col-span-5">{education.period}</p>
            <div className="lg:col-span-7">
              <p className="text-ink">{education.degree}</p>
              <p className="t-meta mt-1">{education.org}</p>
            </div>
          </div>
        </div>
      </section>

      <section aria-labelledby="now" className={SECTION}>
        <h2 id="now" className="t-h2" data-reveal="focus">
          What I am doing now
        </h2>
        <ul className="border-line mt-12 max-w-[64ch] border-t">
          {about.now.map((item, index) => (
            <li
              key={item}
              className="t-body text-ink-2 border-line border-b py-5"
              data-reveal="rise"
              style={stagger(index)}
            >
              {item}
            </li>
          ))}
        </ul>
      </section>

      {/* the only place on the site the stack is listed */}
      <section aria-labelledby="tools" className={SECTION}>
        <div className="flex flex-wrap items-baseline justify-between gap-x-8 gap-y-3">
          <h2 id="tools" className="t-h2" data-reveal="focus">
            Tools
          </h2>
          <p className="t-meta" data-reveal="fade">
            Grouped by how often they are in my hands
          </p>
        </div>
        <div className="border-line mt-12 grid gap-10 border-t pt-10 md:grid-cols-3 md:gap-10">
          {stackGroups.map((group, index) => (
            <div key={group.label} data-reveal="rise" style={stagger(index)}>
              <h3 className="t-voice text-ink">{group.label}</h3>
              <p className="t-meta mt-2">{group.note}</p>
              <Dotted items={group.items} className="t-body text-ink-2 mt-5" />
            </div>
          ))}
        </div>

        <div className="border-line mt-12 border-t pt-10" data-reveal="fade">
          <h3 className="t-voice text-ink">Capabilities</h3>
          <Dotted items={capabilities} className="t-body text-ink-2 mt-5" />
        </div>
      </section>

      <nav aria-label="Next" className={SECTION}>
        <ul className="list border-line border-t">
          {[
            { label: "See the work", href: "/work" },
            { label: "Get in touch", href: "/contact" },
          ].map((link) => (
            <li key={link.href} className="row border-line border-b">
              <Link
                href={link.href}
                className="flex min-h-11 items-center justify-between gap-6 py-6"
              >
                <span className="name t-h3 text-ink font-[350]">
                  {link.label}
                </span>
                <span
                  className="arr t-h3 text-muted font-[350]"
                  aria-hidden="true"
                >
                  →
                </span>
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </div>
  );
}
