import type { CSSProperties } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { contact, meta, profile } from "@/content/site";
import Avatar from "@/components/Avatar";
import AvailDot from "@/components/AvailDot";
import BookCallLink from "@/components/BookCallLink";
import EmailLink from "@/components/EmailLink";
import LightUp from "@/components/LightUp";
import WhatsAppLink from "@/components/WhatsAppLink";
import CopyEmail from "@/components/islands/CopyEmail";
import LocalTime from "@/components/islands/LocalTime";

const TITLE = `Contact — ${profile.short} Tehseen`;
const DESCRIPTION =
  "Hire Muhammad Ammaad Tehseen — full-stack and AI engineer in Lahore, Pakistan, taking freelance projects. Email, WhatsApp or a 30-minute call; remote, any timezone.";

/**
 * The root share card, named explicitly. A page that sets its own openGraph
 * replaces the layout's whole object, and the card generated by
 * app/opengraph-image.tsx only attaches to the segment it lives in, so without
 * this line /contact would share as a bare link.
 */
const SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${profile.name} — ${profile.role} in ${profile.location}`,
};

export const metadata: Metadata = {
  title: "Contact",
  description: DESCRIPTION,
  alternates: { canonical: "/contact" },
  openGraph: {
    type: "website",
    url: `${profile.site}/contact`,
    siteName: meta.title,
    locale: "en_GB",
    title: TITLE,
    description: contact.lede,
    images: [SHARE_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: contact.lede,
    creator: "@MAmmaadTehseen",
    images: [SHARE_IMAGE],
  },
};

/** One section's worth of space: the site rhythm, applied once between sections rather than doubled. */
const SECTION = "mt-[clamp(96px,14vh,160px)]";

const stagger = (i: number) => ({ "--i": i }) as CSSProperties;

/** Label column and action column of a channel row; the label drops above the action on phones. */
const CHANNEL_ROW =
  "row border-line grid items-center gap-x-10 gap-y-3 border-b py-7 md:grid-cols-12 md:py-9";
const CHANNEL_LABEL = "meta t-meta md:col-span-3";
const CHANNEL_ACTION = "min-w-0 md:col-span-9";

/**
 * The ask itself, so it has no closing room (ClosingGate drops it on this
 * path) and the footer ends on its bottom row.
 *
 * The channels are ranked, not offered as equals: a call first, because it is
 * the fastest way to a yes or a no, then WhatsApp, then email, which carries
 * the voice-sized address and a Copy button beside it. They are rows on
 * hairlines rather than cards, sharing the site's focus-dimming.
 *
 * Everything down to the channels can sit in the first viewport, so none of
 * it carries a reveal; reveals begin with the lists below.
 */
export default function ContactPage() {
  return (
    <div className="frame pt-36 pb-[clamp(96px,14vh,160px)] md:pt-44">
      <header className="grid gap-10 lg:grid-cols-12 lg:items-end lg:gap-10">
        <div className="lg:col-span-8">
          <LightUp
            as="h1"
            step={50}
            text={contact.lede}
            className="t-page max-w-[15ch]"
          />
          <p className="t-voice text-ink-2 mt-8 max-w-[34ch]">{contact.body}</p>
        </div>

        {/* who is on the other end, whether he is taking work, and what time it is there */}
        <div className="t-meta flex items-center gap-5 lg:col-span-4 lg:justify-self-end">
          <Avatar size={72} />
          <div className="space-y-1.5">
            {profile.available && (
              <p className="text-ink-2 flex items-center gap-2.5">
                <AvailDot breathe />
                {profile.availableNote}
              </p>
            )}
            <p>
              <LocalTime variant="sentence" showOffset />
            </p>
          </div>
        </div>
      </header>

      <section aria-labelledby="channels" className="mt-16 md:mt-20">
        <h2 id="channels" className="sr-only">
          Ways to reach me
        </h2>
        <ol className="list border-line border-t">
          <li className={CHANNEL_ROW}>
            <p className={CHANNEL_LABEL}>Call</p>
            <div className={CHANNEL_ACTION}>
              <BookCallLink variant="glint" />
            </div>
          </li>

          <li className={CHANNEL_ROW}>
            <p className={CHANNEL_LABEL}>WhatsApp</p>
            <div className={CHANNEL_ACTION}>
              <WhatsAppLink
                variant="plain"
                className="name t-voice text-ink tabular-nums"
              >
                <span className="sr-only">WhatsApp </span>
                {profile.whatsapp.display}
              </WhatsAppLink>
            </div>
          </li>

          <li className={CHANNEL_ROW}>
            <p className={CHANNEL_LABEL}>Email</p>
            <div
              className={`${CHANNEL_ACTION} flex flex-wrap items-center gap-x-5 gap-y-3`}
            >
              {/* the wrapper slides and dims; the link inherits its colour */}
              <span className="name text-ink max-w-full">
                <EmailLink variant="plain" className="t-voice font-light" />
              </span>
              <CopyEmail />
            </div>
          </li>
        </ol>
      </section>

      <div className={`${SECTION} grid gap-14 md:grid-cols-2 md:gap-10`}>
        <section aria-labelledby="helpful" data-reveal="rise">
          <h2 id="helpful" className="t-h3 text-ink">
            What helps me answer well
          </h2>
          <ul className="border-line mt-8 border-t">
            {contact.helpful.map((item) => (
              <li
                key={item}
                className="t-body text-ink-2 border-line border-b py-4"
              >
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section aria-labelledby="honest" data-reveal="rise" style={stagger(1)}>
          <h2 id="honest" className="t-h3 text-ink">
            Straight answers
          </h2>
          <ul className="border-line mt-8 border-t">
            {contact.honest.map((item) => (
              <li
                key={item}
                className="t-body text-ink-2 border-line border-b py-4"
              >
                {item}
              </li>
            ))}
          </ul>
        </section>
      </div>

      <section aria-labelledby="elsewhere" className={SECTION}>
        <h2 id="elsewhere" className="t-h3 text-ink" data-reveal="focus">
          Elsewhere
        </h2>
        <ul className="list border-line mt-8 border-t">
          {profile.socials.map((social, index) => (
            <li
              key={social.href}
              className="row border-line border-b"
              data-reveal="rise"
              style={stagger(index)}
            >
              <a
                href={social.href}
                target="_blank"
                rel="me noopener noreferrer"
                className="flex min-h-11 flex-wrap items-baseline justify-between gap-x-6 gap-y-1 py-6"
              >
                <span className="name t-voice text-ink">{social.label}</span>
                <span className="meta t-meta inline-flex items-center gap-2 wrap-anywhere">
                  {social.handle}
                  <span className="arr-out" aria-hidden="true">
                    ↗
                  </span>
                </span>
                <span className="sr-only"> (opens in a new tab)</span>
              </a>
            </li>
          ))}
        </ul>
      </section>

      <dl
        className={`${SECTION} border-line grid gap-8 border-t pt-8 sm:grid-cols-3`}
        data-reveal="fade"
      >
        <div>
          <dt className="text-ink font-medium">Based in</dt>
          <dd className="t-meta mt-2">
            {profile.location}
            <span className="block">Works with any timezone</span>
          </dd>
        </div>
        <div>
          <dt className="text-ink font-medium">Open to</dt>
          <dd className="t-meta mt-2">Freelance projects, remote</dd>
        </div>
        <div>
          <dt className="text-ink font-medium">Read first</dt>
          <dd className="mt-2">
            <Link
              href="/work"
              className="text-ink-2 inline-flex items-center gap-1.5"
            >
              <span className="u-link">The work</span>
              <span className="arr" aria-hidden="true">
                →
              </span>
            </Link>
          </dd>
        </div>
      </dl>
    </div>
  );
}
