import type { Metadata } from "next";
import { meta, profile, projects, showcase } from "@/content/site";
import LightUp from "@/components/LightUp";
import TierFilter from "@/components/work/TierFilter";
import WorkIndex from "@/components/work/WorkIndex";

const TITLE = `Work — ${profile.short} Tehseen`;
const DESCRIPTION =
  "Client platforms and products by Muhammad Ammaad Tehseen — oncology trial matching, live virtual tours, AI pricing reports, coliving operations, AI lead conversion, meeting automation and more.";
const SHARE_DESCRIPTION = `${projects.length} builds, disclosed at three depths: open source, live in production, or architecture only.`;

/**
 * The root share card, named explicitly. A page that sets its own openGraph
 * replaces the layout's whole object, and the card generated by
 * app/opengraph-image.tsx only attaches to the segment it lives in, so without
 * this /work would share as a bare link.
 */
const SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${profile.name} — ${profile.role} in ${profile.location}`,
};

export const metadata: Metadata = {
  title: "Work",
  description: DESCRIPTION,
  alternates: { canonical: "/work" },
  openGraph: {
    type: "website",
    url: `${profile.site}/work`,
    siteName: meta.title,
    locale: "en_GB",
    title: TITLE,
    description: SHARE_DESCRIPTION,
    images: [SHARE_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: SHARE_DESCRIPTION,
    creator: "@MAmmaadTehseen",
    images: [SHARE_IMAGE],
  },
};

/**
 * /work: every build, at the depth its source allows.
 *
 * The h1 lights up like the other page titles. The lead's numbers come from
 * the arrays, so adding a project never leaves the sentence wrong. The tier
 * filter and the rows share .tier-scope, which is how the zero-JS :has()
 * filter in globals.css finds both. The closing room follows from the
 * layout's footer.
 */
export default function WorkPage() {
  return (
    <div className="frame pt-36 md:pt-44">
      <header className="max-w-[46rem]">
        <LightUp as="h1" text="Work" step={50} className="t-page" />
        <p className="t-lead mt-6">
          {projects.length} builds. The {showcase.length} below get the full
          treatment; smaller ones follow. What you can see of each depends on
          whether the source is mine to show.
        </p>
      </header>

      <div className="tier-scope mt-12 pb-[clamp(96px,14vh,160px)] md:mt-16">
        <TierFilter className="mb-6 md:mb-8" />
        <WorkIndex />
      </div>
    </div>
  );
}
